apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-app
  template:
    metadata:
      labels:
        app: spark-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: spark-app
        image: abhijitdhamne/spark-pi:8913c4a 557d8de }}
        imagePullPolicy: "Always"
        ports:
        - containerPort: 4040
