apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-pi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-pi
  template:
    metadata:
      labels:
        app: spark-pi
    spec:
      containers:
        - name: spark-pi-container
          image: apache/spark:3.5.1-scala2.12-java17-python3-r-ubuntu
          ports:
            - containerPort: 8080 # Assuming your Spark application runs on port 8080
