apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-app
  template:
    metadata:
      labels:
        app: spark-app
    spec:
      containers:
      - name: spark-app
        image: abhijitdhamne/spark-pi:${{ steps.commit_id.outputs.commit_id }}  # Use specific tag (e.g., commit ID)
        ports:
        - containerPort: 4040  # Assuming this is the port your Spark application exposes
