
kind: Service
apiVersion: v1
metadata:
  name: spark-master
spec:
  ports:
     - name: ui
     port: 8080
     targetPort: 8080
     - name: spark
     port: 6000
     targetPort: 6000
  selector:
     component: spark-master
