apiVersion: v1
kind: Service
metadata:
  name: spark-pi-service
spec:
  selector:
    app: spark-pi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32000 # Assuming your Spark application runs on port 8080
  type: NodePOrt # Change to NodePort or ClusterIP depending on your requirements
