apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-pi
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/Abhijit2714/spark-app.git
    path: ./
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
