apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-pi
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/yourusername/your-repo.git
    path: path/to/spark-pi
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
