name: Build and Deploy Spark App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Copy custom folder
      run: |
          sudo mkdir -p /home/user/spark-app
          cp -r app/* /home/user/spark-app
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Get commit ID
      id: commit_id
      run: echo "::set-output name=commit_id::$(git rev-parse --short HEAD)"

    - name: Build and push Docker image
      run: |
        docker build -t abhijitdhamne/spark-pi:latest -t abhijitdhamne/spark-pi:${{ steps.commit_id.outputs.commit_id }} .
        docker push abhijitdhamne/spark-pi:latest
        docker push abhijitdhamne/spark-pi:${{ steps.commit_id.outputs.commit_id }}

    - name: Update deployment YAML with latest commit ID
      run: |
        sed -i "s|abhijitdhamne/spark-pi:{{TAG_PLACEHOLDER}}|abhijitdhamne/spark-pi:${{ steps.commit_id.outputs.commit_id }}|g" argocd/deploment.yaml


