name: Build, Push Docker Image, and Update Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
    - name: Build and push Docker image
      run: |
        docker build -t abhijitdhamne/spark-pi:${{ github.sha }} .
        docker push abhijitdhamne/spark-pi:${{ github.sha }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Get commit ID
      id: commit_id
      run: echo "::set-output name=commit_id::$(git rev-parse --short HEAD)"
      
    - name: Update Deployment Manifest
      run: |
        sed -i "s|abhijitdhamne/spark-pi:latest|abhijitdhamne/spark-pi:${{ steps.commit_id.outputs.commit_id }}|g" argocd/deploment.yaml
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add argocd/deploment.yaml
        git commit -m "Update image tag in deployment.yaml"
        git push origin main
