name: Build, Push Docker Image, and Update Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Copy custom folder
      run: |
          sudo mkdir -p /home/user/spark-app
          cp -r app/* /home/user/spark-app
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
    - name: Get commit ID
      id: commit_id
      run: echo "::set-output name=commit_id::$(git rev-parse --short HEAD)"
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: abhijitdhamne/spark-pi:${{ steps.commit_id.outputs.commit_id }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Update deployment YAML with latest commit ID
      run: |
        # Get the latest commit ID
        COMMIT_ID=$(git rev-parse --short HEAD)
        
        # Set the deployment YAML file path
        DEPLOYMENT_FILE="argocd/deploment.yaml"

        # Replace the image tag placeholder with the latest commit ID
        sed -i "s|abhijitdhamne/spark-pi:latest|abhijitdhamne/spark-pi:${COMMIT_ID}|g" ${DEPLOYMENT_FILE}
        
        echo "Updated deployment.yaml with the latest commit ID: ${COMMIT_ID}"
        
        # Commit and push changes back to the repository
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add ${DEPLOYMENT_FILE}
        git commit -m "Update deployment.yaml with latest commit ID"
        git push
